import './style.css'
import './hero.css'
import { parseMailFile, reconcile, sha256 } from './parser'
import type { ArchiveReport } from './types'

const dbName = 'archive-audit';
function dbGet(): Promise<ArchiveReport | null> { return new Promise((resolve) => { const r = indexedDB.open(dbName, 1); r.onupgradeneeded = () => r.result.createObjectStore('reports'); r.onsuccess = () => { const q = r.result.transaction('reports').objectStore('reports').get('latest'); q.onsuccess = () => resolve(q.result || null); q.onerror = () => resolve(null) }; r.onerror = () => resolve(null) }) }
function dbSave(report: ArchiveReport): Promise<void> { return new Promise((resolve) => { const r = indexedDB.open(dbName, 1); r.onupgradeneeded = () => r.result.createObjectStore('reports'); r.onsuccess = () => { r.result.transaction('reports', 'readwrite').objectStore('reports').put(report, 'latest').onsuccess = () => resolve() }; r.onerror = () => resolve() }) }

let report: ArchiveReport | null = null
let mailInput: HTMLInputElement, folderInput: HTMLInputElement, results: HTMLElement, announce: HTMLElement
const $ = <T extends HTMLElement>(s: string) => document.querySelector<T>(s)!
const escape = (s: string) => s.replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c]!))
const plural = (n: number, word: string) => `${n.toLocaleString()} ${word}${n === 1 ? '' : 's'}`

function app() {
  document.querySelector('#app')!.innerHTML = `
  <header class="top"><a class="brand" href="/" aria-label="Archive Audit home"><span class="brand-mark">✓</span> Archive Audit</a><nav aria-label="Product links"><a href="#how">How it works</a><a href="/privacy/">Privacy</a><button class="quiet" id="theme" aria-label="Switch color theme">◐</button></nav></header>
  <main id="main" tabindex="-1">
    <section class="intro" aria-labelledby="page-title"><div><p class="eyebrow">Local archive inspection</p><h1 id="page-title">Keep the evidence. Check the gaps.</h1><p class="lede">Open an MBOX or EML export on this device. Archive Audit counts messages, verifies embedded attachments, matches attachment folders, and makes a receipt you can keep.</p><p class="quiet-copy">Nothing is uploaded. It runs in your browser, even after installation.</p></div><figure class="notebook-art"><img src="/hero-notebook.webp" width="640" height="640" decoding="async" fetchpriority="high" alt="A field notebook beside a sealed envelope, paperclip, attachment photographs, and verification mark."><figcaption>Original generated notebook study</figcaption></figure></section>
    <section class="workspace" aria-labelledby="audit-heading"><div class="section-heading"><p class="eyebrow">New audit</p><h2 id="audit-heading">Put your export on the desk</h2></div><div class="drop-grid"><label class="dropzone" for="mail-files"><strong>Message exports</strong><span>MBOX or EML files</span><input id="mail-files" type="file" accept=".mbox,.eml,message/rfc822" multiple></label><label class="dropzone optional" for="attachment-files"><strong>Attachment folder <small>optional</small></strong><span>Choose files from the exported attachment folder</span><input id="attachment-files" type="file" multiple webkitdirectory></label></div><div class="actions"><button id="audit" class="primary">Audit selected files</button><button id="example" class="quiet">Load a safe example</button></div><p class="limit">Format limits: reads standard MIME EML and text MBOX exports. Encrypted, proprietary, and provider-only stores cannot be inspected here.</p></section>
    <section id="results" class="results" aria-live="polite"></section>
    <section id="how" class="how"><p class="eyebrow">Method note</p><h2>What the receipt can prove</h2><ol><li>It inventories the MBOX/EML files you gave it.</li><li>It hashes readable embedded attachment bytes with SHA-256.</li><li>It names missing or separately supplied attachment references. It does not contact any mail provider.</li></ol></section>
    <section class="unlock" aria-labelledby="unlock-title"><div><p class="eyebrow">Optional one-time unlock</p><h2 id="unlock-title">Keep a signed index sheet</h2><p>The free audit, CSV, JSON and HTML receipt are permanent. An optional one-time upgrade adds a signed index sheet and retained audit history. Price is shown at secure checkout.</p></div><div><a class="buy primary" href="https://api.sociobot.in/api/v1/products/message-archive-audit/checkout">View one-time upgrade</a><details><summary>Already have a license?</summary><label for="license">Paste your license token</label><div class="restore"><input id="license" autocomplete="off"><button id="restore" class="quiet">Restore</button></div><p id="license-state" class="quiet-copy"></p></details></div></section>
  </main><footer>Made for archive handoffs, not account access. Artwork is AI-generated, product data stays on this device. <a href="/terms/">Terms</a></footer><div id="announce" class="sr-only" aria-live="polite"></div><div id="toast" class="toast" hidden></div>`
  mailInput = $('#mail-files'); folderInput = $('#attachment-files'); results = $('#results'); announce = $('#announce')
  $('#audit').addEventListener('click', audit); $('#example').addEventListener('click', example); $('#theme').addEventListener('click', toggleTheme); $('#restore').addEventListener('click', restoreLicense)
  const params = new URLSearchParams(location.search); const license = params.get('license'); if (license) { localStorage.setItem('sb_license:message-archive-audit', license); history.replaceState({}, '', location.pathname); verifyLicense(license) } else verifyLicense(localStorage.getItem('sb_license:message-archive-audit'))
}

async function audit() {
  const mails = [...mailInput.files || []].filter(f => /\.(eml|mbox)$/i.test(f.name))
  if (!mails.length) return feedback('Choose at least one .eml or .mbox file before auditing.')
  results.innerHTML = `<div class="working"><span></span>Reading ${plural(mails.length, 'export')} locally…</div>`; announce.textContent = 'Audit in progress'
  try {
    const folderFiles = await Promise.all([...folderInput.files || []].map(async f => ({ name: f.name, size: f.size, hash: await sha256(await f.arrayBuffer()) })))
    const messageGroups = await Promise.all(mails.map(parseMailFile)); const messages = messageGroups.flat()
    reconcile(messages, folderFiles)
    const missing = messages.flatMap(m => m.attachments).filter(a => a.status === 'missing').length
    report = { id: crypto.randomUUID(), createdAt: new Date().toISOString(), sources: mails.map(f => f.name), messages, folderFiles, issues: missing ? [`${plural(missing, 'attachment reference')} could not be found in the supplied folder.`] : [] }
    await dbSave(report); renderReport(); announce.textContent = `Audit complete. ${plural(messages.length, 'message')} found.`
  } catch (error) { feedback(`Could not read this export. Try a standard text MBOX or EML file. ${error instanceof Error ? error.message : ''}`) }
}

async function example() {
  const raw = `From: Sam <sam@example.test>\nSubject: Trip record\nDate: Tue, 02 Jan 2024 10:00:00 +0000\nContent-Type: multipart/mixed; boundary=archive\n\n--archive\nContent-Type: text/plain\n\nHere is the receipt.\n--archive\nContent-Type: text/plain; name="ticket.txt"\nContent-Disposition: attachment; filename="ticket.txt"\nContent-Transfer-Encoding: base64\n\naGVsbG8gYXJjaGl2ZQ==\n--archive--`
  const dt = new DataTransfer(); dt.items.add(new File([raw], 'example.eml', { type:'message/rfc822' })); mailInput.files = dt.files; await audit()
}

function renderReport() {
  if (!report) return; const attachments = report.messages.flatMap(m => m.attachments); const verified = attachments.filter(a => a.status === 'verified').length; const missing = attachments.filter(a => a.status === 'missing').length
  results.innerHTML = `<div class="receipt-head"><div><p class="eyebrow">Audit receipt</p><h2>${missing ? 'Needs a closer look' : 'Archive inventory complete'}</h2><p class="quiet-copy">Created ${new Date(report.createdAt).toLocaleString()} · saved locally on this device</p></div><div class="stamp ${missing ? 'warn' : ''}">${missing ? 'CHECK GAPS' : 'VERIFIED'}<small>local record</small></div></div><div class="metrics"><div><b>${report.messages.length}</b><span>messages</span></div><div><b>${attachments.length}</b><span>attachments named</span></div><div><b>${verified}</b><span>embedded & hashed</span></div><div><b>${missing}</b><span>references missing</span></div></div>${report.issues.length ? `<div class="issue" role="status"><strong>Attention needed</strong><p>${report.issues.map(escape).join(' ')}</p><p>Choose the exported attachment folder and audit again, or keep this receipt as evidence that these files were not present.</p></div>` : `<div class="good"><strong>No broken attachment references found.</strong> Embedded attachments were decoded and hashed locally.</div>`}<div class="report-actions"><button id="html" class="primary">Save HTML receipt</button><button id="csv" class="quiet">Export CSV</button><button id="json" class="quiet">Export JSON</button><button id="clear" class="quiet danger">Clear local report</button></div><details class="ledger" open><summary>Message ledger — ${plural(report.messages.length, 'message')}</summary><div class="table-wrap"><table><thead><tr><th>Message</th><th>Attachment</th><th>Status</th><th>SHA-256</th></tr></thead><tbody>${report.messages.map(m => m.attachments.length ? m.attachments.map(a => `<tr><td><b>${escape(m.subject)}</b><small>${escape(m.from)} · ${escape(m.date)}</small></td><td>${escape(a.name)}<small>${a.size == null ? 'No readable bytes' : `${a.size.toLocaleString()} bytes`}</small></td><td><span class="status ${a.status}">${a.status === 'verified' ? 'Embedded & hashed' : a.status === 'missing' ? 'Missing from folder' : 'Found separately'}</span></td><td class="hash">${a.hash || '—'}</td></tr>`).join('') : `<tr><td><b>${escape(m.subject)}</b><small>${escape(m.from)} · ${escape(m.date)}</small></td><td>—</td><td><span class="status">No attachment</span></td><td>—</td></tr>`).join('')}</tbody></table></div></details>`
  $('#html').addEventListener('click', () => download('archive-audit-receipt.html', receiptHtml(), 'text/html')); $('#csv').addEventListener('click', () => download('archive-audit.csv', csv(), 'text/csv')); $('#json').addEventListener('click', () => download('archive-audit.json', JSON.stringify(report, null, 2), 'application/json')); $('#clear').addEventListener('click', clearReport)
}

function csv() { if (!report) return ''; const q = (s: unknown) => `"${String(s ?? '').replaceAll('"', '""')}"`; return ['Subject,From,Date,Attachment,Status,SHA-256', ...report.messages.flatMap(m => m.attachments.map(a => [m.subject,m.from,m.date,a.name,a.status,a.hash || ''].map(q).join(',')))].join('\n') }
function receiptHtml() { if (!report) return ''; return `<!doctype html><html lang="en"><meta charset="utf-8"><title>Archive Audit receipt</title><style>body{font:16px system-ui;max-width:920px;margin:40px auto;padding:0 20px;color:#20261f;background:#f6f0e2}h1{font-family:Georgia,serif}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #b9b5a8;text-align:left;vertical-align:top}.hash{font:12px ui-monospace,monospace;word-break:break-all}.ok{color:#176547}.missing{color:#a33b2b}</style><h1>Archive Audit receipt</h1><p>Created: ${escape(report.createdAt)}<br>Sources: ${report.sources.map(escape).join(', ')}</p><h2>Summary</h2><p>${report.messages.length} messages · ${report.messages.flatMap(m=>m.attachments).length} attachments named · ${report.issues.join(' ') || 'No broken references found.'}</p><table><thead><tr><th>Message</th><th>Attachment</th><th>Status</th><th>SHA-256</th></tr></thead><tbody>${report.messages.flatMap(m => m.attachments.map(a => `<tr><td>${escape(m.subject)}</td><td>${escape(a.name)}</td><td class="${a.status === 'verified'?'ok':'missing'}">${escape(a.status)}</td><td class="hash">${a.hash || '—'}</td></tr>`)).join('')}</tbody></table><p>This receipt was generated locally by Archive Audit. It does not certify a provider export or prove that unselected source data did not exist.</p></html>` }
function download(name:string, content:string, type:string) { const url = URL.createObjectURL(new Blob([content], {type})); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(()=>URL.revokeObjectURL(url), 2000) }
function feedback(message:string) { results.innerHTML = `<div class="issue"><strong>Couldn’t start the audit</strong><p>${escape(message)}</p></div>`; announce.textContent = message }
async function clearReport() { if (!confirm('Clear the saved local audit report? This does not delete your source files.')) return; report = null; await new Promise<void>(resolve => { const r=indexedDB.open(dbName); r.onsuccess=()=>{r.result.transaction('reports','readwrite').objectStore('reports').delete('latest').onsuccess=()=>resolve()} }); results.innerHTML = ''; feedback('Local report cleared. Your selected source files were never stored.') }
function toggleTheme(){ document.documentElement.dataset.theme = document.documentElement.dataset.theme === 'dark' ? '' : 'dark' }
async function restoreLicense(){ const value = $('#license') as HTMLInputElement; if (!value.value.trim()) return; localStorage.setItem('sb_license:message-archive-audit', value.value.trim()); await verifyLicense(value.value.trim()) }
async function verifyLicense(token: string | null) { const state = document.querySelector('#license-state'); if (!token || !state) return; const old = localStorage.getItem('sb_license_verdict:message-archive-audit'); if (old) { const cached = JSON.parse(old); if (Date.now() - cached.at < 86400000) { state.textContent = cached.valid ? 'License restored.' : 'License no longer active.'; return } } state.textContent = 'Checking license…'; try { const r = await fetch(`https://api.sociobot.in/api/v1/products/message-archive-audit/verify?license=${encodeURIComponent(token)}`); const v = await r.json(); localStorage.setItem('sb_license_verdict:message-archive-audit', JSON.stringify({valid:!!v.valid,at:Date.now()})); state.textContent = v.valid ? 'License restored.' : 'License no longer active. You can purchase a new upgrade anytime.' } catch { state.textContent = 'License will be checked when you are online.' } }

app(); dbGet().then(saved => { if (saved) { report = saved; renderReport(); announce.textContent = 'Saved local audit restored.' } });
if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').then(reg => { reg.addEventListener('updatefound', () => { const toast = $('#toast'); toast.hidden = false; toast.innerHTML = `A new offline version is ready. <button>Refresh</button>`; toast.querySelector('button')!.addEventListener('click', () => reg.waiting?.postMessage('skip-waiting')) }); navigator.serviceWorker.addEventListener('controllerchange', () => location.reload()) });
